# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    steps:
      - checkout
      - run: echo "this is the test job"
      - run: ls
      - run: df -h
      - run: nproc
      
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
    # Run the welcome/run job in its own container

      
