version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: list
          command: ls
      - run:
          name: list
          command: df -h
      - run:
          name: list
          command: nproc
